[package]
name = "stq_types"
version = "0.1.0"

[dependencies]
derive_more = "*"
failure = "0.1"
futures = "0.1"
serde = "*"
serde_derive = "*"
serde_json = "*"
stq_acl = { path = "../acl" }
stq_db = { path = "../db" }
uuid = { version = "*", features = ["serde", "v4"] }
