[package]
name = "stq_http"
version = "0.1.0"

[dependencies]
failure = ">=0.1.2"
futures = "0.1"
hyper = "0.11"
hyper-tls="0.1.3"
juniper = "0.9.2"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
validator = "0.6"
chrono = "0.4"
