[package]
name = "stq_http"
version = "0.1.0"

[dependencies]
failure = "*"
futures = "0.1"
hyper = "0.11"
juniper = "0.9"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
validator = "*"
