[package]
name = "stq_db"
version = "0.1.0"

[dependencies]
futures = "0.1"
futures-state-stream = "0.2"
postgres = { git = "https://github.com/sfackler/rust-postgres" }
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres", features = ["with-serde_json"] }
